// autogenerated by sql-generate v1.1.0 on Thu Oct 15 2015 11:18:13 GMT+0200 (CEST)

var sql = require('sql');


exports.combined = sql.define({
	name: 'combined',
	schema: 'schiedam',
	columns: [
		{ name: 'date' },
		{ name: 'name' },
		{ name: 'bu_code' },
        { name: 'dumps' },
        { name: 'fillperc' }
	]
});
/**
 * SQL definition for schiedam.aantal_meldingen_per_buurt_juni
 */
exports.aantal_meldingen_per_buurt_juni = sql.define({
	name: 'aantal_meldingen_per_buurt_juni',
	schema: 'schiedam',
	columns: [
		{ name: 'count' },
		{ name: 'bu_code' },
		{ name: 'bu_naam' }
	]
});


/**
 * SQL definition for schiedam.buurten
 */
exports.buurten = sql.define({
	name: 'buurten',
	schema: 'schiedam',
	columns: [
		{ name: 'gid' },
		{ name: 'bu_code' },
		{ name: 'bu_naam' },
		{ name: 'wk_code' },
		{ name: 'gm_code' },
		{ name: 'gm_naam' },
		{ name: 'water' },
		{ name: 'aant_inw' },
		{ name: 'aant_man' },
		{ name: 'aant_vrouw' },
		{ name: 'p_00_14_jr' },
		{ name: 'p_15_24_jr' },
		{ name: 'p_25_44_jr' },
		{ name: 'p_45_64_jr' },
		{ name: 'p_65_eo_jr' },
		{ name: 'p_ongehuwd' },
		{ name: 'p_gehuwd' },
		{ name: 'p_gescheid' },
		{ name: 'p_verweduw' },
		{ name: 'bev_dichth' },
		{ name: 'aantal_hh' },
		{ name: 'p_eenp_hh' },
		{ name: 'p_hh_z_k' },
		{ name: 'p_hh_m_k' },
		{ name: 'gem_hh_gr' },
		{ name: 'p_west_al' },
		{ name: 'p_n_w_al' },
		{ name: 'p_marokko' },
		{ name: 'p_ant_aru' },
		{ name: 'p_surinam' },
		{ name: 'p_turkije' },
		{ name: 'p_over_nw' },
		{ name: 'auto_tot' },
		{ name: 'auto_hh' },
		{ name: 'auto_land' },
		{ name: 'bedr_auto' },
		{ name: 'motor_2w' },
		{ name: 'a_lftj6j' },
		{ name: 'a_lfto6j' },
		{ name: 'a_bst_b' },
		{ name: 'a_bst_nb' },
		{ name: 'opp_tot' },
		{ name: 'opp_land' },
		{ name: 'opp_water' },
		{ name: 'geom' }
	]
});


/**
 * SQL definition for schiedam.container_locaties
 */
exports.container_locaties = sql.define({
	name: 'container_locaties',
	schema: 'schiedam',
	columns: [
		{ name: 'ogc_fid' },
		{ name: 'wkb_geometry' },
		{ name: 'unieknr' },
		{ name: 'lokatie' },
		{ name: 'type' },
		{ name: 'model' },
		{ name: 'soort' },
		{ name: 'locatie' },
		{ name: 'thv' },
		{ name: 'wijk' },
		{ name: 'sdm01' },
		{ name: 'houder' },
		{ name: 'cyclus' },
		{ name: 'ophaald' },
		{ name: 'omschr' },
		{ name: 'mut_dat' },
		{ name: 'mutatie' },
		{ name: 'rd_x' },
		{ name: 'rd_y' },
		{ name: 'latitude' },
		{ name: 'longitude' },
		{ name: 'gps_n_e' }
	]
});


/**
 * SQL definition for schiedam.containers
 */
exports.containers = sql.define({
	name: 'containers',
	schema: 'schiedam',
	columns: [
		{ name: 'wkb_geometry' },
		{ name: 'unieknr' },
		{ name: 'locatie' },
		{ name: 'thv' },
		{ name: 'nummer' },
		{ name: 'soort' },
		{ name: 'maximum aantal stortingen' },
		{ name: 'trommel (liter)' },
		{ name: 'capaciteit (m3)' },
		{ name: 'wijkcode' },
		{ name: 'buurtcode' }
	]
});


/**
 * SQL definition for schiedam.containers_maxstort
 */
exports.containers_maxstort = sql.define({
	name: 'containers_maxstort',
	schema: 'schiedam',
	columns: [
		{ name: 'ogc_fid' },
		{ name: 'nummer' },
		{ name: 'type' },
		{ name: 'fractie' },
		{ name: 'maximum aantal stortingen' },
		{ name: 'trommel (liter)' },
		{ name: 'capaciteit (m3)' }
	]
});


/**
 * SQL definition for schiedam.containers_natu_nass
 */
exports.containers_natu_nass = sql.define({
	name: 'containers_natu_nass',
	schema: 'schiedam',
	columns: [
		{ name: 'x_coord' },
		{ name: 'y_coord' },
		{ name: 'unieknr' },
		{ name: 'locatie' },
		{ name: 'thv' },
		{ name: 'nummer' },
		{ name: 'soort' },
		{ name: 'maximum aantal stortingen' },
		{ name: 'trommel (liter)' },
		{ name: 'capaciteit (m3)' },
		{ name: 'bu_code' },
		{ name: 'bu_naam' },
		{ name: 'wk_code' },
		{ name: 'wk_naam' }
	]
});


/**
 * SQL definition for schiedam.containers_wijbu
 */
exports.containers_wijbu = sql.define({
	name: 'containers_wijbu',
	schema: 'schiedam',
	columns: [
		{ name: 'x_coord' },
		{ name: 'y_coord' },
		{ name: 'unieknr' },
		{ name: 'locatie' },
		{ name: 'thv' },
		{ name: 'nummer' },
		{ name: 'soort' },
		{ name: 'maximum aantal stortingen' },
		{ name: 'trommel (liter)' },
		{ name: 'capaciteit (m3)' },
		{ name: 'bu_code' },
		{ name: 'bu_naam' },
		{ name: 'wk_code' },
		{ name: 'wk_naam' }
	]
});


/**
 * SQL definition for schiedam.empty_juni2015
 */
exports.empty_juni2015 = sql.define({
	name: 'empty_juni2015',
	schema: 'schiedam',
	columns: [
		{ name: 'ogc_fid' },
		{ name: 'timestamp' },
		{ name: 'container' },
		{ name: 'vulgraad' }
	]
});


/**
 * SQL definition for schiedam.geocoded1
 */
exports.geocoded1 = sql.define({
	name: 'geocoded1',
	schema: 'schiedam',
	columns: [
		{ name: 'ogc_fid' },
		{ name: 'identification' },
		{ name: 'case_type_code' },
		{ name: 'channel_code' },
		{ name: 'description' },
		{ name: 'clarification' },
		{ name: 'registration_date' },
		{ name: 'start_date' },
		{ name: 'end_date' },
		{ name: 'planned_end_date' },
		{ name: 'completion_date' },
		{ name: 'publication_date' },
		{ name: 'case_level' },
		{ name: 'sub_case_indication' },
		{ name: 'archive_nomination' },
		{ name: 'archive_indication' },
		{ name: 'case_type_id' },
		{ name: 'payment_indication' },
		{ name: 'last_payment_date' },
		{ name: 'confidentiality_level' },
		{ name: 'anonymous' },
		{ name: 'urgency_level' },
		{ name: 'niveau1case' },
		{ name: 'niveau2case' },
		{ name: 'niveau3case' },
		{ name: 'adres' },
		{ name: 'postcode' },
		{ name: 'woonplaats' },
		{ name: 'x_coordinaat' },
		{ name: 'y_coordinaat' },
		{ name: 'z_coordinaat' },
		{ name: 'cat_comb' },
		{ name: 'geom' },
		{ name: 'geopunt' }
	]
});


/**
 * SQL definition for schiedam.legingen
 */
exports.legingen = sql.define({
	name: 'legingen',
	schema: 'schiedam',
	columns: [
		{ name: 'ogc_fid' },
		{ name: 'regmoment' },
		{ name: 'dumplocnum' },
		{ name: 'dumplocdesc' },
		{ name: 'containernum' },
		{ name: 'containerdesc' },
		{ name: 'fillperc' }
	]
});


/**
 * SQL definition for schiedam.legingen_natu_nass
 */
exports.legingen_natu_nass = sql.define({
	name: 'legingen_natu_nass',
	schema: 'schiedam',
	columns: [
		{ name: 'ogc_fid' },
		{ name: 'regmoment' },
		{ name: 'dumplocnum' },
		{ name: 'dumplocdesc' },
		{ name: 'containernum' },
		{ name: 'containerdesc' },
		{ name: 'fillperc' },
		{ name: 'x_coord' },
		{ name: 'y_coord' },
		{ name: 'unieknr' },
		{ name: 'locatie' },
		{ name: 'thv' },
		{ name: 'nummer' },
		{ name: 'soort' },
		{ name: 'maximum aantal stortingen' },
		{ name: 'trommel (liter)' },
		{ name: 'capaciteit (m3)' },
		{ name: 'bu_code' },
		{ name: 'bu_naam' },
		{ name: 'wk_code' },
		{ name: 'wk_naam' },
		{ name: 'geom' }
	]
});


/**
 * SQL definition for schiedam.meldingen
 */
exports.meldingen = sql.define({
	name: 'meldingen',
	schema: 'schiedam',
	columns: [
		{ name: 'ogc_fid' },
		{ name: 'id' },
		{ name: 'identification' },
		{ name: 'case_type_code' },
		{ name: 'channel_code' },
		{ name: 'description' },
		{ name: 'clarification' },
		{ name: 'registration_date' },
		{ name: 'start_date' },
		{ name: 'end_date' },
		{ name: 'planned_end_date' },
		{ name: 'completion_date' },
		{ name: 'publication_date' },
		{ name: 'case_level' },
		{ name: 'sub_case_indication' },
		{ name: 'archive_nomination' },
		{ name: 'archive_indication' },
		{ name: 'case_type_id' },
		{ name: 'payment_indication' },
		{ name: 'last_payment_date' },
		{ name: 'confidentiality_level' },
		{ name: 'anonymous' },
		{ name: 'urgency_level' },
		{ name: 'niveau1case' },
		{ name: 'niveau2case' },
		{ name: 'niveau3case' },
		{ name: 'adres' },
		{ name: 'postcode' },
		{ name: 'woonplaats' },
		{ name: 'x_coordinaat' },
		{ name: 'y_coordinaat' },
		{ name: 'z_coordinaat' }
	]
});


/**
 * SQL definition for schiedam.meldingen2
 */
exports.meldingen2 = sql.define({
	name: 'meldingen2',
	schema: 'schiedam',
	columns: [
		{ name: 'ogc_fid' },
		{ name: 'identification' },
		{ name: 'case_type_code' },
		{ name: 'channel_code' },
		{ name: 'description' },
		{ name: 'clarification' },
		{ name: 'registration_date' },
		{ name: 'start_date' },
		{ name: 'end_date' },
		{ name: 'planned_end_date' },
		{ name: 'completion_date' },
		{ name: 'publication_date' },
		{ name: 'case_level' },
		{ name: 'sub_case_indication' },
		{ name: 'archive_nomination' },
		{ name: 'archive_indication' },
		{ name: 'case_type_id' },
		{ name: 'payment_indication' },
		{ name: 'last_payment_date' },
		{ name: 'confidentiality_level' },
		{ name: 'anonymous' },
		{ name: 'urgency_level' },
		{ name: 'niveau1case' },
		{ name: 'niveau2case' },
		{ name: 'niveau3case' },
		{ name: 'adres' },
		{ name: 'postcode' },
		{ name: 'woonplaats' },
		{ name: 'x_coordinaat' },
		{ name: 'y_coordinaat' },
		{ name: 'z_coordinaat' }
	]
});


/**
 * SQL definition for schiedam.meldingen_2015_12
 */
exports.meldingen_2015_12 = sql.define({
	name: 'meldingen_2015_12',
	schema: 'schiedam',
	columns: [
		{ name: 'id' },
		{ name: 'identification' },
		{ name: 'case_type_code' },
		{ name: 'channel_code' },
		{ name: 'description' },
		{ name: 'clarification' },
		{ name: 'registration_date' },
		{ name: 'start_date' },
		{ name: 'end_date' },
		{ name: 'planned_end_date' },
		{ name: 'completion_date' },
		{ name: 'publication_date' },
		{ name: 'case_level' },
		{ name: 'sub_case_indication' },
		{ name: 'archive_nomination' },
		{ name: 'archive_indication' },
		{ name: 'case_type_id' },
		{ name: 'payment_indication' },
		{ name: 'last_payment_date' },
		{ name: 'confidentiality_level' },
		{ name: 'anonymous' },
		{ name: 'urgency_level' },
		{ name: 'niveau1case' },
		{ name: 'niveau2case' },
		{ name: 'niveau3case' },
		{ name: 'straatnaam' },
		{ name: 'huisnummer' },
		{ name: 'huisletter' },
		{ name: 'locatie_omschrijving' },
		{ name: 'postcode' },
		{ name: 'buurt' },
		{ name: 'wijk' },
		{ name: 'woonplaats' },
		{ name: 'xcoord' },
		{ name: 'ycoord' },
		{ name: 'precision' },
		{ name: 'geom' }
	]
});


/**
 * SQL definition for schiedam.meldingen_all_geocoded
 */
exports.meldingen_all_geocoded = sql.define({
	name: 'meldingen_all_geocoded',
	schema: 'schiedam',
	columns: [
		{ name: 'ogc_fid' },
		{ name: 'identification' },
		{ name: 'case_type_code' },
		{ name: 'channel_code' },
		{ name: 'description' },
		{ name: 'clarification' },
		{ name: 'registration_date' },
		{ name: 'start_date' },
		{ name: 'end_date' },
		{ name: 'planned_end_date' },
		{ name: 'completion_date' },
		{ name: 'publication_date' },
		{ name: 'case_level' },
		{ name: 'sub_case_indication' },
		{ name: 'archive_nomination' },
		{ name: 'archive_indication' },
		{ name: 'case_type_id' },
		{ name: 'payment_indication' },
		{ name: 'last_payment_date' },
		{ name: 'confidentiality_level' },
		{ name: 'anonymous' },
		{ name: 'urgency_level' },
		{ name: 'niveau1case' },
		{ name: 'niveau2case' },
		{ name: 'niveau3case' },
		{ name: 'adres' },
		{ name: 'postcode' },
		{ name: 'woonplaats' },
		{ name: 'x_coordinaat' },
		{ name: 'y_coordinaat' },
		{ name: 'z_coordinaat' },
		{ name: 'geopunt' }
	]
});


/**
 * SQL definition for schiedam.meldingen_all_met_buurt
 */
exports.meldingen_all_met_buurt = sql.define({
	name: 'meldingen_all_met_buurt',
	schema: 'schiedam',
	columns: [
		{ name: 'ogc_fid' },
		{ name: 'identification' },
		{ name: 'case_type_code' },
		{ name: 'channel_code' },
		{ name: 'description' },
		{ name: 'clarification' },
		{ name: 'registration_date' },
		{ name: 'start_date' },
		{ name: 'end_date' },
		{ name: 'planned_end_date' },
		{ name: 'completion_date' },
		{ name: 'publication_date' },
		{ name: 'case_level' },
		{ name: 'sub_case_indication' },
		{ name: 'archive_nomination' },
		{ name: 'archive_indication' },
		{ name: 'case_type_id' },
		{ name: 'payment_indication' },
		{ name: 'last_payment_date' },
		{ name: 'confidentiality_level' },
		{ name: 'anonymous' },
		{ name: 'urgency_level' },
		{ name: 'niveau1case' },
		{ name: 'niveau2case' },
		{ name: 'niveau3case' },
		{ name: 'adres' },
		{ name: 'postcode' },
		{ name: 'woonplaats' },
		{ name: 'x_coordinaat' },
		{ name: 'y_coordinaat' },
		{ name: 'z_coordinaat' },
		{ name: 'geopunt' },
		{ name: 'bu_code' },
		{ name: 'bu_naam' }
	]
});


/**
 * SQL definition for schiedam.meldingen_grouped_buurt_month
 */
exports.meldingen_grouped_buurt_month = sql.define({
	name: 'meldingen_grouped_buurt_month',
	schema: 'schiedam',
	columns: [
		{ name: 'bu_naam' },
		{ name: 'mon' },
		{ name: 'year' },
		{ name: 'count' },
		{ name: 'ym' }
	]
});


/**
 * SQL definition for schiedam.meldingen_jan_bu_week
 */
exports.meldingen_jan_bu_week = sql.define({
	name: 'meldingen_jan_bu_week',
	schema: 'schiedam',
	columns: [
		{ name: 'bu_code' },
		{ name: 'week' },
		{ name: 'count' }
	]
});


/**
 * SQL definition for schiedam.meldingen_juni
 */
exports.meldingen_juni = sql.define({
	name: 'meldingen_juni',
	schema: 'schiedam',
	columns: [
		{ name: 'ogc_fid' },
		{ name: 'identification' },
		{ name: 'case_type_code' },
		{ name: 'channel_code' },
		{ name: 'description' },
		{ name: 'clarification' },
		{ name: 'registration_date' },
		{ name: 'start_date' },
		{ name: 'end_date' },
		{ name: 'planned_end_date' },
		{ name: 'completion_date' },
		{ name: 'publication_date' },
		{ name: 'case_level' },
		{ name: 'sub_case_indication' },
		{ name: 'archive_nomination' },
		{ name: 'archive_indication' },
		{ name: 'case_type_id' },
		{ name: 'payment_indication' },
		{ name: 'last_payment_date' },
		{ name: 'confidentiality_level' },
		{ name: 'anonymous' },
		{ name: 'urgency_level' },
		{ name: 'niveau1case' },
		{ name: 'niveau2case' },
		{ name: 'niveau3case' },
		{ name: 'adres' },
		{ name: 'postcode' },
		{ name: 'woonplaats' },
		{ name: 'x_coordinaat' },
		{ name: 'y_coordinaat' },
		{ name: 'z_coordinaat' },
		{ name: 'cat_comb' },
		{ name: 'geom' }
	]
});


/**
 * SQL definition for schiedam.meldingen_juni_met_buurt
 */
exports.meldingen_juni_met_buurt = sql.define({
	name: 'meldingen_juni_met_buurt',
	schema: 'schiedam',
	columns: [
		{ name: 'ogc_fid' },
		{ name: 'identification' },
		{ name: 'case_type_code' },
		{ name: 'channel_code' },
		{ name: 'description' },
		{ name: 'clarification' },
		{ name: 'registration_date' },
		{ name: 'start_date' },
		{ name: 'end_date' },
		{ name: 'planned_end_date' },
		{ name: 'completion_date' },
		{ name: 'publication_date' },
		{ name: 'case_level' },
		{ name: 'sub_case_indication' },
		{ name: 'archive_nomination' },
		{ name: 'archive_indication' },
		{ name: 'case_type_id' },
		{ name: 'payment_indication' },
		{ name: 'last_payment_date' },
		{ name: 'confidentiality_level' },
		{ name: 'anonymous' },
		{ name: 'urgency_level' },
		{ name: 'niveau1case' },
		{ name: 'niveau2case' },
		{ name: 'niveau3case' },
		{ name: 'adres' },
		{ name: 'postcode' },
		{ name: 'woonplaats' },
		{ name: 'x_coordinaat' },
		{ name: 'y_coordinaat' },
		{ name: 'z_coordinaat' },
		{ name: 'cat_comb' },
		{ name: 'geom' },
		{ name: 'geopunt' },
		{ name: 'bu_code' },
		{ name: 'bu_naam' }
	]
});


/**
 * SQL definition for schiedam.meldingen_per_buurt_per_month
 */
exports.meldingen_per_buurt_per_month = sql.define({
	name: 'meldingen_per_buurt_per_month',
	schema: 'schiedam',
	columns: [
		{ name: 'bu_naam' },
		{ name: '_201110' },
		{ name: '_201111' },
		{ name: '_201112' },
		{ name: '_20115' },
		{ name: '_20117' },
		{ name: '_20118' },
		{ name: '_20119' },
		{ name: '_201210' },
		{ name: '_201211' },
		{ name: '_201212' },
		{ name: '_20121' },
		{ name: '_20122' },
		{ name: '_20123' },
		{ name: '_20124' },
		{ name: '_20125' },
		{ name: '_20126' },
		{ name: '_20127' },
		{ name: '_20128' },
		{ name: '_20129' },
		{ name: '_201310' },
		{ name: '_201311' },
		{ name: '_201312' },
		{ name: '_20131' },
		{ name: '_20132' },
		{ name: '_20133' },
		{ name: '_20134' },
		{ name: '_20135' },
		{ name: '_20136' },
		{ name: '_20137' },
		{ name: '_20138' },
		{ name: '_20139' },
		{ name: '_201410' },
		{ name: '_201411' },
		{ name: '_201412' },
		{ name: '_20141' },
		{ name: '_20142' },
		{ name: '_20143' },
		{ name: '_20144' },
		{ name: '_20145' },
		{ name: '_20146' },
		{ name: '_20147' },
		{ name: '_20148' },
		{ name: '_20149' },
		{ name: '_20151' },
		{ name: '_20152' },
		{ name: '_20153' },
		{ name: '_20154' },
		{ name: '_20155' },
		{ name: '_20156' }
	]
});


/**
 * SQL definition for schiedam.ontbrekende_containers
 */
exports.ontbrekende_containers = sql.define({
	name: 'ontbrekende_containers',
	schema: 'schiedam',
	columns: [
		{ name: 'id' },
		{ name: 'geom' },
		{ name: 'field_1' },
		{ name: 'field_2' },
		{ name: '51.938680,4.387008' },
		{ name: 'EL-1590' },
		{ name: 'field_5' },
		{ name: 'gro 100' },
		{ name: 'SPA-008' },
		{ name: 'Ringvaart 125' },
		{ name: 'field_9' },
		{ name: 'field_10' },
		{ name: 'ja' },
		{ name: 'field_12' },
		{ name: '3124 PB' },
		{ name: 'SPALANDSVE' },
		{ name: 'Schiedam' },
		{ name: '11/22/2013 10:50' },
		{ name: 'IMG_2998.JPG' },
		{ name: 'Rest' },
		{ name: 'field_19' },
		{ name: 'Kraan' },
		{ name: 'field_21' },
		{ name: 'Kraan ondergronds' },
		{ name: 'Metro opname' },
		{ name: 'Sulo Champignon' },
		{ name: 'field_25' },
		{ name: 'MOD' },
		{ name: '#N/A' },
		{ name: 'auto 48-vr-Matera' },
		{ name: 'field_29' },
		{ name: 'field_30' },
		{ name: 'field_31' },
		{ name: 'field_32' },
		{ name: 'field_33' },
		{ name: '11/22/2013' },
		{ name: 'field_35' },
		{ name: 'Irado' },
		{ name: 'buurtnaam' },
		{ name: 'buurtcode' }
	]
});


/**
 * SQL definition for schiedam.ontbrekende_containers_geocoded
 */
exports.ontbrekende_containers_geocoded = sql.define({
	name: 'ontbrekende_containers_geocoded',
	schema: 'schiedam',
	columns: [
		{ name: 'bu_naam' },
		{ name: 'bu_code' },
		{ name: 'id' },
		{ name: 'geom' },
		{ name: 'field_1' },
		{ name: 'field_2' },
		{ name: '51.938680,4.387008' },
		{ name: 'EL-1590' },
		{ name: 'field_5' },
		{ name: 'gro 100' },
		{ name: 'SPA-008' },
		{ name: 'Ringvaart 125' },
		{ name: 'field_9' },
		{ name: 'field_10' },
		{ name: 'ja' },
		{ name: 'field_12' },
		{ name: '3124 PB' },
		{ name: 'SPALANDSVE' },
		{ name: 'Schiedam' },
		{ name: '11/22/2013 10:50' },
		{ name: 'IMG_2998.JPG' },
		{ name: 'Rest' },
		{ name: 'field_19' },
		{ name: 'Kraan' },
		{ name: 'field_21' },
		{ name: 'Kraan ondergronds' },
		{ name: 'Metro opname' },
		{ name: 'Sulo Champignon' },
		{ name: 'field_25' },
		{ name: 'MOD' },
		{ name: '#N/A' },
		{ name: 'auto 48-vr-Matera' },
		{ name: 'field_29' },
		{ name: 'field_30' },
		{ name: 'field_31' },
		{ name: 'field_32' },
		{ name: 'field_33' },
		{ name: '11/22/2013' },
		{ name: 'field_35' },
		{ name: 'Irado' },
		{ name: 'buurtnaam' },
		{ name: 'buurtcode' }
	]
});


/**
 * SQL definition for schiedam.stortingen_2015_06
 */
exports.stortingen_2015_06 = sql.define({
	name: 'stortingen_2015_06',
	schema: 'schiedam',
	columns: [
		{ name: 'ogc_fid' },
		{ name: 'beschrijving' },
		{ name: 'adres' },
		{ name: 'container_id' },
		{ name: 'timestamp' },
		{ name: 'vulgraad' }
	]
});


/**
 * SQL definition for schiedam.stortingen_2015_12
 */
exports.stortingen_2015_12 = sql.define({
	name: 'stortingen_2015_12',
	schema: 'schiedam',
	columns: [
		{ name: 'date' },
		{ name: 'name' },
		{ name: 'dumps' }
	]
});


/**
 * SQL definition for schiedam.stortingen_all
 */
exports.stortingen_all = sql.define({
	name: 'stortingen_all',
	schema: 'schiedam',
	columns: [
		{ name: 'ogc_fid' },
		{ name: 'unitid' },
		{ name: 'regmoment' },
		{ name: 'regtype' },
		{ name: 'regnum' },
		{ name: 'chipnum' },
		{ name: 'success' },
		{ name: 'dumplocnum' }
	]
});


/**
 * SQL definition for schiedam.stortingen_jan
 */
exports.stortingen_jan = sql.define({
	name: 'stortingen_jan',
	schema: 'schiedam',
	columns: [
		{ name: 'ogc_fid' },
		{ name: 'dag' },
		{ name: 'bu_naam' },
		{ name: 'totaal' }
	]
});


/**
 * SQL definition for schiedam.stortingen_jan_bu_week
 */
exports.stortingen_jan_bu_week = sql.define({
	name: 'stortingen_jan_bu_week',
	schema: 'schiedam',
	columns: [
		{ name: 'bu_code' },
		{ name: 'week' },
		{ name: 'count' }
	]
});


/**
 * SQL definition for schiedam.stort_leeg_natu_nass
 */
exports.stort_leeg_natu_nass = sql.define({
	name: 'stort_leeg_natu_nass',
	schema: 'schiedam',
	columns: [
		{ name: 'container_id' },
		{ name: 'timestamp' },
		{ name: 'type' }
	]
});


/**
 * SQL definition for schiedam.vulgraad_jan
 */
exports.vulgraad_jan = sql.define({
	name: 'vulgraad_jan',
	schema: 'schiedam',
	columns: [
		{ name: 'ogc_fid' },
		{ name: 'dag' },
		{ name: 'buurt' },
		{ name: 'fillpercentage' }
	]
});


/**
 * SQL definition for schiedam.vulling_jan_bu_week
 */
exports.vulling_jan_bu_week = sql.define({
	name: 'vulling_jan_bu_week',
	schema: 'schiedam',
	columns: [
		{ name: 'bu_code' },
		{ name: 'week' },
		{ name: 'avgfill' }
	]
});


/**
 * SQL definition for schiedam.vullingsgraad_2015_12
 */
exports.vullingsgraad_2015_12 = sql.define({
	name: 'vullingsgraad_2015_12',
	schema: 'schiedam',
	columns: [
		{ name: 'date' },
		{ name: 'name' },
		{ name: 'fillperc' }
	]
});


/**
 * SQL definition for schiedam.wegvakken
 */
exports.wegvakken = sql.define({
	name: 'wegvakken',
	schema: 'schiedam',
	columns: [
		{ name: 'id' },
		{ name: 'geom' },
		{ name: 'wvk_id' },
		{ name: 'wvk_begdat' },
		{ name: 'jte_id_beg' },
		{ name: 'jte_id_end' },
		{ name: 'wegbehsrt' },
		{ name: 'wegnummer' },
		{ name: 'wegdeelltr' },
		{ name: 'hecto_lttr' },
		{ name: 'baansubsrt' },
		{ name: 'rpe_code' },
		{ name: 'admrichtng' },
		{ name: 'rijrichtng' },
		{ name: 'stt_naam' },
		{ name: 'wpsnaamnen' },
		{ name: 'gme_id' },
		{ name: 'gme_naam' },
		{ name: 'hnrstrlnks' },
		{ name: 'hnrstrrhts' },
		{ name: 'e_hnr_lnks' },
		{ name: 'e_hnr_rhts' },
		{ name: 'l_hnr_lnks' },
		{ name: 'l_hnr_rhts' },
		{ name: 'begafstand' },
		{ name: 'endafstand' },
		{ name: 'beginkm' },
		{ name: 'eindkm' },
		{ name: 'pos_tv_wol' }
	]
});


/**
 * SQL definition for schiedam.wijken
 */
exports.wijken = sql.define({
	name: 'wijken',
	schema: 'schiedam',
	columns: [
		{ name: 'gid' },
		{ name: 'wk_code' },
		{ name: 'wk_naam' },
		{ name: 'gm_code' },
		{ name: 'gm_naam' },
		{ name: 'water' },
		{ name: 'aant_inw' },
		{ name: 'aant_man' },
		{ name: 'aant_vrouw' },
		{ name: 'p_00_14_jr' },
		{ name: 'p_15_24_jr' },
		{ name: 'p_25_44_jr' },
		{ name: 'p_45_64_jr' },
		{ name: 'p_65_eo_jr' },
		{ name: 'p_ongehuwd' },
		{ name: 'p_gehuwd' },
		{ name: 'p_gescheid' },
		{ name: 'p_verweduw' },
		{ name: 'bev_dichth' },
		{ name: 'aantal_hh' },
		{ name: 'p_eenp_hh' },
		{ name: 'p_hh_z_k' },
		{ name: 'p_hh_m_k' },
		{ name: 'gem_hh_gr' },
		{ name: 'p_west_al' },
		{ name: 'p_n_w_al' },
		{ name: 'p_marokko' },
		{ name: 'p_ant_aru' },
		{ name: 'p_surinam' },
		{ name: 'p_turkije' },
		{ name: 'p_over_nw' },
		{ name: 'auto_tot' },
		{ name: 'auto_hh' },
		{ name: 'auto_land' },
		{ name: 'bedr_auto' },
		{ name: 'motor_2w' },
		{ name: 'a_lftj6j' },
		{ name: 'a_lfto6j' },
		{ name: 'a_bst_b' },
		{ name: 'a_bst_nb' },
		{ name: 'opp_tot' },
		{ name: 'opp_land' },
		{ name: 'opp_water' },
		{ name: 'geom' }
	]
});


